TABLESIZE = 10

if TABLESIZE % 2:
    raise ValueError("TABLESIZE must be an even number!" )

CELLSIZE = 40

FRAMESIZE = TABLESIZE * CELLSIZE

COLOUR_1 = "blue"
COLOUR_2 = "deeppink"
BG_COLOUR = "white"
SPECIAL_COLOUR = "grey"

MAXDEPTH = 2

COMPUTER_SIGN = 2
PLAYER_SIGN = 1
CENTER_SIGN = 3
